# Generated by Django 2.2.1 on 2019-05-14 18:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug_name', models.SlugField(blank=True, editable=False, help_text='Unique slug name slug name', max_length=100, unique=True)),
                ('publisher', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=255)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
