# Generated by Django 2.2.1 on 2019-05-15 07:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text='Book author name', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Book object creation date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(default=0, help_text='Total no. of pages in book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(help_text='Book publisher name', max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], help_text='List of tags'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Book title', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Book object updation date'),
        ),
    ]
